/* Copiloto de ECG — imagens e textos de referência pedidos pelo Dr. Vitor.
   Cada item nasce com validada:false e só aparece no modo revisão. Os 17 primeiros foram validados pelo Dr. Vitor em 23/09/2026. Quando o Dr. Vitor aprova
   (revisao-imagens.html), vira validada:true e passa a aparecer para todo mundo.
   Imagens: recortes do LITFL (CC BY-NC-SA 4.0) em app/ref/, com as marcações em azul feitas por nós. */
const REFS = {
  // etapa 2
  calibracao:{legenda:"Antes de ler, confira no rodapé a velocidade (25 mm/s) e o ganho (10 mm/mV), e veja se o pulso de calibração tem 10 mm de altura.", alt:"Faixa inferior de um eletrocardiograma impresso em papel milimetrado: à esquerda, o pulso de calibração retangular antes do traçado de V1; embaixo, à direita, o texto impresso '25 mm/s' e '10 mm/mV'. Os dois pontos estão contornados por retângulos azuis.", arquivo:"ref/calibracao.webp", largura:1000, altura:240, credito:"Wikimedia Commons · Rodhullandemu · Domínio público", pagina:"https://commons.wikimedia.org/wiki/File:Normal_ECG_from_a_66-year_old_British_male_subject_2019.jpg", validada:true},
  eletrodos:{legenda:"Eletrodos dos membros nos punhos e nos tornozelos, no padrão de cores IEC. Em aparelhos com o padrão americano (AHA) as cores mudam: confira as siglas RA, LA, RL e LL.", alt:"Esquema de uma pessoa de frente com quatro eletrodos: vermelho no punho direito, amarelo no punho esquerdo, preto no tornozelo direito e verde no tornozelo esquerdo.", arquivo:"ref/eletrodos.webp", largura:900, altura:900, credito:"Esquema do Copiloto", pagina:"", validada:true},
  // etapa 3
  "p-dii":{legenda:"Em DII, no ritmo sinusal, cada QRS vem depois de uma onda P positiva, sempre com a mesma forma.", alt:"Cerca de 5 segundos da derivação DII de um ECG normal em ritmo sinusal. Cinco setas azuis apontam para as ondas P positivas antes de cada QRS.", arquivo:"ref/p-dii.webp", largura:1000, altura:175, credito:"Wikimedia Commons · Rodhullandemu · Domínio público", pagina:"https://commons.wikimedia.org/wiki/File:Normal_ECG_from_a_66-year_old_British_male_subject_2019.jpg", validada:true},
  "p-polaridade":{legenda:"No ritmo sinusal, a P é positiva em DI, DII e aVF e negativa em aVR.", alt:"Mosaico 2 por 2 com um batimento de cada derivação: DI, DII, aVF e aVR, do mesmo ECG normal. Um círculo azul marca a onda P em cada painel: positiva em DI, DII e aVF e negativa em aVR.", arquivo:"ref/p-polaridade.webp", largura:618, altura:380, credito:"Wikimedia Commons · Rodhullandemu · Domínio público", pagina:"https://commons.wikimedia.org/wiki/File:Normal_ECG_from_a_66-year_old_British_male_subject_2019.jpg", validada:true},
  // etapa 7
  supra:{tipo:"texto", validada:true, credito:"4ª Definição Universal de Infarto (Thygesen et al., 2018)",
    html:`<p>Supra de ST novo, medido no ponto J, em pelo menos duas derivações contíguas:</p>
      <div class="crit"><p><b>V2–V3:</b> ≥ 2 mm em homens com 40 anos ou mais · ≥ 2,5 mm em homens com menos de 40 anos · ≥ 1,5 mm em mulheres, em qualquer idade</p>
      <p><b>Demais derivações:</b> ≥ 1 mm</p>
      <p><b>V7–V9 (posteriores):</b> ≥ 0,5 mm</p>
      <p><b>V3R–V4R (direitas):</b> ≥ 0,5 mm</p></div>
      <p class="tiny mute">Critérios válidos na ausência de hipertrofia de VE e de bloqueio de ramo esquerdo.</p>`},
  wellens:{legenda:"Wellens tipo B: T profundamente invertida e simétrica nas precordiais (V2–V6), sem supra de ST relevante e sem onda Q.", alt:"Derivações precordiais V1 a V6 com ondas T profundamente invertidas e simétricas de V2 a V6, segmento ST praticamente isoelétrico e progressão de onda R preservada.", arquivo:"ref/wellens.webp", largura:600, altura:473, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/wellens-syndrome-ecg-library/", validada:true, junto:["wellens-a"], caracteristicas:[
    "T bifásica (tipo A) ou profundamente invertida e simétrica (tipo B) em V2–V3, às vezes até V4–V6",
    "Pouco ou nenhum supra de ST, sem onda Q e com progressão da onda R preservada",
    "Costuma aparecer quando a dor já passou; sugere estenose crítica da DA proximal"]},
  // tipo A pedido pelo Dr. Vitor na validação de 23/09 e aprovado em 24/09; aparece junto do tipo B, dentro de "wellens"
  "wellens-a":{legenda:"Wellens tipo A: T bifásica em V2–V3, primeiro positiva e depois negativa, sem supra de ST relevante.", alt:"Derivações precordiais V1 a V6. Em V2 e V3, ondas T bifásicas, com uma porção inicial positiva seguida de uma porção terminal negativa (circuladas em azul). ST sem supradesnivelamento relevante.", arquivo:"ref/wellens-a.webp", largura:555, altura:400, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/wellens-syndrome-ecg-library/", validada:true},
  dewinter:{legenda:"de Winter: infra do ponto J com ST ascendente emendando em T alta e simétrica nas precordiais, com supra discreto em aVR.", alt:"ECG de 12 derivações sem o ritmo longo. De V2 a V4, infradesnivelamento do ponto J com ST ascendente que emenda em ondas T altas, largas e simétricas. Em aVR, discreto supradesnivelamento de ST. Um círculo azul marca o complexo de V3 e outro o ST de aVR.", arquivo:"ref/dewinter.webp", largura:1000, altura:329, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/de-winter-t-wave/", validada:true, caracteristicas:[
    "Infra do ponto J de 1 a 3 mm nas precordiais, com ST ascendente",
    "Ondas T altas, apiculadas e simétricas logo depois do infra",
    "Supra discreto em aVR é frequente; é equivalente de oclusão da DA proximal"]},
  aslanger:{legenda:"Aslanger: supra de ST só em DIII, ST em V1 maior que em V2 e infra em V4–V6 com T positiva — IAM inferior sem critério clássico de supra.", alt:"ECG de 12 derivações montado em duas colunas: à esquerda DI, DII, DIII, aVR, aVL e aVF; à direita V1 a V6. Supra de ST discreto só em DIII (circulado), ST de V1 acima do de V2 (ambos circulados) e infra de ST em V4 e V5 com onda T positiva (setas).", arquivo:"ref/aslanger.webp", largura:1000, altura:704, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/aslanger-pattern/", validada:true, caracteristicas:[
    "Supra de ST em DIII, sem supra em DII e aVF",
    "Infra de ST em V4–V6 com T positiva ou terminalmente positiva, sem infra em V2",
    "ST em V1 mais alto que em V2; sugere infarto inferior com doença multiarterial"]},
  avr:{legenda:"Infra de ST difuso com supra em aVR: isquemia subendocárdica difusa, padrão associado a lesão de tronco ou multiarterial.", alt:"ECG de 12 derivações com taquicardia sinusal. Infra de ST horizontal difuso, mais evidente em V4 a V6 e em DI e DII, com supradesnivelamento de ST em aVR (circulado). Setas azuis apontam o infra em V4 e V5.", arquivo:"ref/avr.webp", largura:1000, altura:377, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/myocardial-ischaemia-ecg-library/", validada:true, caracteristicas:[
    "Infra de ST difuso, mais evidente em DI, DII e V4–V6",
    "Supra de ST em aVR, em geral ≥ 1 mm e maior que em V1",
    "Isquemia subendocárdica difusa: pode indicar lesão de tronco ou multiarterial, mas também ocorre por taquicardia, hipotensão ou anemia"]},
  hiper:{legenda:"T hiperagudas em V2–V3: altas, de base larga e desproporcionais ao QRS, fase precoce de IAM anterior.", alt:"Derivações V2 e V3 com ondas T muito altas e de base larga, maiores que o QRS que as precede, com ST retificado subindo direto para a T.", arquivo:"ref/hiper.webp", largura:480, altura:555, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/t-wave-ecg-library/", validada:true, caracteristicas:[
    "Ondas T largas na base, volumosas e desproporcionais ao QRS",
    "Aparecem nos primeiros minutos da oclusão, antes do supra, nas derivações de um mesmo território",
    "Compare com as derivações vizinhas e com ECG prévio; repetir o ECG em poucos minutos ajuda"]},
  // etapa 8
  "qrs-inicio-fim":{legenda:"A duração do QRS vai da primeira deflexão depois do segmento PR até o ponto J, onde a onda S volta à linha de base.", alt:"Derivação DII de um ECG real em papel milimetrado. Um batimento com QRS estreito aparece à direita, com uma linha azul vertical no começo do QRS e outra no ponto J, ligadas embaixo por um colchete. À esquerda aparecem o rótulo II e um primeiro batimento com ruído de início de registro.", arquivo:"ref/qrs-inicio-fim.webp", largura:620, altura:270, credito:"Wikimedia Commons · Peterhcharlton · CC BY 4.0", pagina:"https://commons.wikimedia.org/wiki/File:12_lead_ECG.jpg", validada:true},
  "v1-brd-bre":{legenda:"Em V1, o bloqueio de ramo direito termina para cima (rsR', a 'orelha de coelho') e o esquerdo termina para baixo (S larga e profunda).", alt:"Duas faixas da derivação V1 lado a lado. À esquerda, bloqueio de ramo direito: QRS com padrão rsR', com um r pequeno, um s e um R' alto e largo, seguido de onda T invertida. À direita, bloqueio de ramo esquerdo: QRS largo e predominantemente negativo, com r mínimo e S profunda, seguida de supradesnivelamento do ST discordante.", arquivo:"ref/v1-brd-bre.webp", largura:612, altura:132, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/right-bundle-branch-block-rbbb-ecg-library/ + https://litfl.com/left-bundle-branch-block-lbbb-ecg-library/", validada:true},
  // etapa 10
  s1q3t3:{legenda:"Padrão S1Q3T3 no TEP: S profunda em DI, Q e T invertida em DIII.", alt:"Derivações DI e DIII lado a lado de um ECG de embolia pulmonar maciça. Em DI, uma seta azul aponta para a onda S profunda. Em DIII, uma seta azul aponta para a onda Q e outra para a onda T invertida.", arquivo:"ref/s1q3t3.webp", largura:640, altura:150, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/ecg-changes-in-pulmonary-embolism/", validada:true},
  hk1:{legenda:"Hipercalemia (K 7,0): ondas T altas, estreitas e apiculadas, mais evidentes de V2 a V4.", alt:"Derivações precordiais V1 a V6 de um ECG com hipercalemia (potássio 7,0): ondas T altas, estreitas, simétricas e pontiagudas, maiores de V2 a V4. Círculos azuis marcam uma onda T em V2 e outra em V4.", arquivo:"ref/hk1.webp", largura:605, altura:475, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/hyperkalaemia-ecg-library/", validada:true},
  hk2:{legenda:"Hipercalemia grave (K 9,9): QRS largo fundido com a T, formando o padrão sinusoidal.", alt:"ECG com hipercalemia grave (potássio 9,9): QRS muito alargado que se funde com a onda T, formando ondas contínuas em forma de seno, sem ondas P visíveis. Seta azul aponta um dos complexos na tira de ritmo em DII.", arquivo:"ref/hk2.webp", largura:1000, altura:308, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/hyperkalaemia-ecg-library/", validada:true},
  hpk1:{legenda:"Hipocalemia: ondas T achatadas de forma difusa, em quase todas as derivações.", alt:"ECG de 12 derivações com hipocalemia: ondas T achatadas, quase planas, de forma generalizada. Círculos azuis marcam a região da onda T em DI e em V5.", arquivo:"ref/hpk1.webp", largura:791, altura:279, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/t-wave-ecg-library/", validada:true},
  hpk2:{legenda:"Hipocalemia grave (K 1,7): onda T invertida seguida de onda U proeminente, bem vista de V3 a V5.", alt:"Precordiais V1 a V6 de um ECG com hipocalemia grave (potássio 1,7): em V4, depois do QRS, infradesnível do ST com onda T invertida, seguida de uma onda U grande e arredondada. Círculo azul na onda T e seta azul na onda U.", arquivo:"ref/hpk2.webp", largura:590, altura:470, credito:"LITFL · CC BY-NC-SA 4.0", pagina:"https://litfl.com/hypokalaemia-ecg-library/", validada:true},
};
if (typeof module !== "undefined") module.exports = REFS;
